version: 2
updates:
  - package-ecosystem: bun
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '03:00'
      timezone: Asia/Jakarta
    open-pull-requests-limit: 5
    groups:
      bun-minor-and-patch:
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: typescript
        update-types:
          - version-update:semver-major
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    labels:
      - dependencies
      - github-actions

  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: monthly
    labels:
      - dependencies
      - docker
